import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Main from '@/components/Main'
import About from '@/components/About'
import Skills from '@/components/Skills'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'
import Resume from '@/components/Resume'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='lg:snap-y lg:snap-mandatory scroll-smooth'>
      <Head>
        <title>Patrick's Portfolio Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />

      <About />

      <Skills />

      <Resume />

      <Projects />

      <Contact />

    </div>
  )
}
